set(TEST_DRIVER_INCLUDE_FILE "/Users/aleksandrsuslin/desktop/webview/test_driver/cmake/discovery.cmake")
set(TEST_DRIVER_CONFIG_FILE_BASE "/Users/aleksandrsuslin/desktop/webview/core/tests/webview_core_unit_tests_test_driver")
set(TEST_TIMEOUT "10")
set(TEST_TIMEOUT_AFTER_MATCH "")
include("${TEST_DRIVER_INCLUDE_FILE}")
set(TEST_DRIVER_SINGLE_CONFIG_FILE "${TEST_DRIVER_CONFIG_FILE_BASE}.cmake")
set(TEST_DRIVER_MULTI_CONFIG_FILE "${TEST_DRIVER_CONFIG_FILE_BASE}-${CTEST_CONFIGURATION_TYPE}.cmake")
if(EXISTS "${TEST_DRIVER_MULTI_CONFIG_FILE}")
   include("${TEST_DRIVER_MULTI_CONFIG_FILE}")
else()
   include("${TEST_DRIVER_SINGLE_CONFIG_FILE}")
endif()
webview_discover_tests_impl("${TEST_DRIVER}")
